name: CI and Release

on:
  merge_group:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.read-go-version.outputs.go-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: debug .go-version file
        run: cat .go-version

      - name: Read .go-version file
        id: read-go-version
        run: |
          echo "go-version=(cat .go-version)" >> $GITHUB_OUTPUT

  debug:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.setup.outputs.go-version }}
  go:
    needs: setup
    uses: ./.github/workflows/go-ci.yml
    with:
      go-version: ${{ needs.setup.outputs.go-version }}

  publish:
    needs: go
    uses: ./.github/workflows/publish.yml

  release:
    name: Release
    needs: setup
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.setup.outputs.go-version }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
