name: CI and Release

on:
  merge_group:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

env:
  GO_VERSION: '1.21'

jobs:
  go:
    uses: ./.github/workflows/go-ci.yml
    with:
      go-version: "${{ env.GO_VERSION }}"

  publish:
    needs: go
    uses: ./.github/workflows/publish.yml

  release:
    name: Release
    needs: go
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
