name: CI and Release

on:
  merge_group:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  setup:
      runs-on: ubuntu-latest
      inputs:
        go-version:
          description: 'Go version'
          required: true
          type: string
          default: '1.21'
      outputs:
        go_version: ${{ steps.set-vars.outputs.go-version }}
      steps:
      - id: set-vars
        run: echo "::set-output name=go-version::${{ inputs.go-version }}"

  go:
    needs: setup
    uses: ./.github/workflows/go-ci.yml
    with:
      go-version: ${{ needs.setup.outputs.go_version }}

  publish:
    needs: go
    uses: ./.github/workflows/publish.yml

  release:
    name: Release
    needs: go
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.setup.outputs.go_version }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
