name: upload release docs

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  upload-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "Uploading docs for release ${{ github.event.release.tag_name }}" > file.txt
          gh release upload ${{github.event.release.tag_name}} file.txt
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
