name: Go CI

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        env:
          GO111MODULE: off
        with:
          go-version: ${{ inputs.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 8m --verbose
          version: v1.54
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true

  go_mod_tidy_check:
    name: Go Mod Tidy Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - run: go mod tidy

      - name: check for diff
        run: git diff --exit-code

  test:
    needs: [lint, go_mod_tidy_check]
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run tests
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

